# fly.toml app configuration file generated for mini-youtube-purple-night-3043 on 2023-12-02T11:43:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mini-youtube-purple-night-3043"
primary_region = "scl"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
