"""agregando columna de fecha de actualización

Revision ID: 1754fbf37ee3
Revises: 34860e63a250
Create Date: 2023-09-21 00:37:54.600611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1754fbf37ee3'
down_revision = '34860e63a250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')

    # ### end Alembic commands ###
