"""agregando columna de fecha

Revision ID: 34860e63a250
Revises: 
Create Date: 2023-09-21 00:32:47.985782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34860e63a250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
